@extends('layouts.master')
@section('navibar')
@include('partial/navibar')
@stop
@section('header')
@include('partial/header')
@stop
@section('portfolio')
@include('partial/portfolio')
@stop
@section('content')
@include('partial/content')
@stop
@section('contact')
@include('partial/contact')
@stop
@section('footer')
@include('partial/footer')
@stop
@section('rest')
@include('partial/rest')
@stop
